name: Deploy React Tic Tac Toe to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
    build-and-deploy:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Bun.js
              uses: oven-sh/setup-bun@v2
              with:
                bun-version: 1.1.21
            - run: bun install --frozen-lockfile
            - name: Build
              run: bun run build-cd
            - name: Deploy
              uses: actions/deploy-pages@v4
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                artifact_name: build
